# Test your FastAPI endpoints

GET http://127.0.0.1:1045/
Accept: application/json

###

GET http://127.0.0.1:1045/hello/User
Accept: application/json

###

POST http://127.0.0.1:1045/inference
Accept: application/json
Content-Type: application/json

{
  "item": "Como crear un factorial recursivamente"
}

###

POST http://127.0.0.1:1045/inference
Accept: application/json
Content-Type: application/json

{
  "item": "Como crear un factorial sin método recursivo"
}


